jobs:
  build:
    environment:
    working_directory: ~/repo
    docker:
      - image: diegosporfie/circleci_openjdk_11_jdk_aws_cli
    steps:
      - checkout
  deploy:
    docker:
      - image: diegosporfie/circleci_openjdk_11_jdk_aws_cli
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: ./gradlew bootBuildImage


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
