jobs:
  build:
    environment:
    working_directory: ~/repo
    docker:
      - image: diegosporfie/circleci_openjdk_11_jdk_aws_cli
    steps:
      - checkout
  deploy:
    docker:
      - image: diegosporfie/circleci_openjdk_11_jdk_aws_cli
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: ./gradlew bootBuildImage
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" — password-stdin 
            docker push castronu/my-sample-project:0.0.1-SNAPSHOT

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
