version: 2
jobs: # a collection of steps
  build:
    environment:
      _JAVA_OPTIONS: -Xmx1g -Xms256m
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:11-jdk
    steps: # a collection of executable commands
      - checkout # check out source code to working directory
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
      - run:
          name: Build and deploy
          # Use "./gradlew test" instead if tests are not run in parallel
          command: |
            ./gradlew bootBuildImage
workflows:
  version: 2
  workflow:
    jobs:
    - build
